# -*- coding: utf-8 -*-
"""my_captain_Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LLWVvopwtDg5e2aRH0WSbnkgiX9whPRr
"""

# Write Python program which accepts the radius of a circle computes area
import math as m

r = float(input("Input the radius of the circle : "))
aoc = m.pi*r*r

print("The area of the circle with radius",r,"is:",aoc)
