# -*- coding: utf-8 -*-
"""my_captain_Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LLWVvopwtDg5e2aRH0WSbnkgiX9whPRr
"""


"""   Assignment 6   """

# Write a Python Program for Fibonacci numbers.

def fibonacci(r):
  first = 0
  second = 1
  for i in range(0,r):
    print(first)                    
    mind = first +second     
    first = second 
    second = mind   

r = int(input("Ener the range of fibonacci sequence : "))
fibonacci(r) 
