# -*- coding: utf-8 -*-
"""my_captain_Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LLWVvopwtDg5e2aRH0WSbnkgiX9whPRr
"""

"""   Assignment 5    """

# Write a Python program to print all positive numbers in a range.

def print_posN(l):
  L = []
  for ele in l:
    if(ele > 0):
      L.append(ele)
  print("Output:",L)  


list1 = [12,-7,5,64,-14]
print("Input : list1 = ",list1)
print_posN(list1)

list2 = [12, 14, -95, 3]
print("Input : list2 = ",list2)
print_posN(list2)
